TRAINING_SET_PARAMETERS = [-15,-15,1; 15,15,1; -15,15,1; 15,-15,1];

NumberOfClasses = length(TRAINING_SET_PARAMETERS);

TRAINING_SET_ELEMENTS_COUNT = 5;

TRAINING_SET = generateRandomTrainingSet(TRAINING_SET_PARAMETERS, TRAINING_SET_ELEMENTS_COUNT);

ELEMENTS = generateRandomCircleSet(0,0,27, 1000);

KERNEL = @kernel_gaussian;